apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "truenas-scale-csi.csiDriverName" . }}
  labels:
    {{- include "truenas-scale-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
  storageCapacity: true