
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ include "truenas-scale-csi.nodeDaemonsetName" . }}
  labels:
    {{- include "truenas-scale-csi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "truenas-scale-csi.nodeSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "truenas-scale-csi.nodeSelectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: node-server
      {{- with .Values.node.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true  # original iscsi connection would be broken without hostNetwork setting
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "truenas-scale-csi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.node.podSecurityContext | nindent 8 }}
      containers:
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port={{ include "truenas-scale-csi.nodeLivenessProbeHealthPort" . }}
            - --v=2
          imagePullPolicy: "IfNotPresent"
          {{- with .Values.sidecars.livenessProbe.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
          args:
            - --v=2
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/{{ include "truenas-scale-csi.csiDriverName" . -}}/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: "IfNotPresent"
          {{- with .Values.sidecars.nodeDriverRegistrar.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name: node-server
          securityContext:
            {{- toYaml .Values.node.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--url=$(TRUENAS_URL)"
            {{- if eq .Values.settings.type "nfs" }}
            - "--nfs-storage-path=$(NFS_PATH)"
            {{- else }}
            - "--iscsi-storage-path=$(ISCSI_PATH)"
            - "--portal=$(PORTAL_ID)"
            {{- end }}
            - "--node-id=$(NODE_ID)"
            - "-v={{ .Values.settings.verbosity }}"
            - "--type=$(CSI_TYPE)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: TRUENAS_URL
              value: {{ .Values.settings.url | quote }}
            {{- if eq .Values.settings.type "nfs" }}
            - name: NFS_PATH
              value: {{ .Values.settings.nfsStoragePath | quote }}
            {{- else }}
            - name: ISCSI_PATH
              value: {{ .Values.settings.iscsiStoragePath | quote }}
            - name: PORTAL_ID
              value: {{ .Values.settings.portalID | quote }}
            {{- end }}
            - name: LOG_LEVEL
              value: {{ (include "truenas-scale-csi.logLevel" .) | quote }}
            - name: CSI_TYPE
              value: {{ .Values.settings.type | quote }}
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: host-dev
              mountPath: /dev
            - name: host-root
              mountPath: /host
              mountPropagation: "HostToContainer"
            {{- if eq .Values.settings.type "iscsi" }}
            - name: iscsi-csi-run-dir
              mountPath: /var/run/iscsi.truenas-scale.terricain.github.com
            {{- end }}
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/{{ include "truenas-scale-csi.csiDriverName" . }}
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: host-dev
          hostPath:
            path: /dev
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: tmp
          emptyDir: {}
        {{- if eq .Values.settings.type "iscsi" }}
        - name: iscsi-csi-run-dir
          hostPath:
            path: /var/run/iscsi.truenas-scale.terricain.github.com
        {{- end }}