apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "truenas-scale-csi.serviceAccountName" . }}
  labels:
    {{- include "truenas-scale-csi.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}