version: "2"

linters:

  exclusions:
    paths:
      - "cmd/truenas-csi-test/.*"
      - "cmd/truenas-iscsi-test/.*"
      # Ignore files looted from iscsi csi driver
      - pkg/driver/iscsi_node_iscsi.go
      - pkg/driver/iscsi_node_utils.go
