
settings:
  type: "nfs" # either `nfs` or `iscsi`

  # defaults to sane unix socket
  endpoint: null

  # -- TrueNAS API URL, e.g. http://192.168.69.69:1339/api/v2.0
  url: ""

  # -- TrueNAS dataset path, create a dataset for dynamically provisioned NFS datasets to
  # be stored under. The path is essentially the name of the storage pool and then any datasets
  # in a directory sort of layout. The following command will list all paths:
  #   curl -s -X GET "http://NAS/api/v2.0/pool/dataset" -H "Authorization: Bearer API_TOKEN" | jq '.[].id'
  nfsStoragePath: ""
  iscsiStoragePath: ""

  # -- TrueNAS portal ID for iSCSI
  #   curl -s -X GET "http://nas01/api/v2.0/iscsi/portal" -H "Authorization: Bearer ${TOKEN}" | jq '.'
  portalID: ""

  # -- Enable debug logs
  enableDebugLogging: false

  # -- TrueNAS Access Token secret, should have a field of "token"
  accessTokenSecretName: ""

storageClass:
  create: true
  annotations: {}
  namePrefix: "truenas-" # Will either be truenas-nfs or truenas-iscsi



# ---
image:
  repository: ghcr.io/terrycain/truenas-scale-csi
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}

controller:
  # More than 1 is not supported yet.
  replicaCount: 1
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

node:
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}

nfsCSIDriverName: "nfs.truenas-scale.terrycain.github.com"
iscsiCSIDriverName: "iscsi.truenas-scale.terrycain.github.com"