name: Release Charts

on:
  push:
    branches:
      - '*'
    paths:
      - 'charts/**'

jobs:
  helm-lint:
    name: helm-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alexellis/setup-arkade@v2
      - uses: alexellis/arkade-get@master
        with:
          kubeconform: latest
          helm: "v3.15.2"
      - name: Validate Helm chart
        run: |
            set -eo pipefail
            helm template ./charts/truenas-scale-csi | kubeconform --kubernetes-version 1.27.0 -output tap

  release:
    needs: helm-lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.15.2"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
